[project]
name = "asgm"
version = "0.1.0"
description = "Async Star Graph Metric"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.78.1",
    "pydantic>=2.11.4",
]

[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'
